/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kEUEDqOqrpN
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "../components/ui/table"
import { Button } from "../components/ui/button"
import { Card } from "../components/ui/card"

export function History({ history }: HistoryProps) {

  return (
    <Card className="w-full mx-auto">
      <Table className="min-w-[600px]">
        <TableHeader>
          <TableRow>
            <TableHead className="w-[200px]">Song Title</TableHead>
            <TableHead>Parody Title</TableHead>
            <TableHead>Artist</TableHead>
            <TableHead>Generation Date</TableHead>
            <TableHead className="justify-center">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {history.map((entry, index) => (
            <TableRow key={index}>
              <TableCell className="font-medium">{entry.songTitle}</TableCell>
              <TableCell>{entry.parodyTitle}</TableCell>
              <TableCell>{entry.artist}</TableCell>
              <TableCell>{entry.generationDate}</TableCell>
              <TableCell className="flex justify-center gap-2">
                {/* Implement view and edit actions if needed */}
                <Button size="sm">View</Button>
                <Button size="sm">Edit</Button>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Card>
  )
}
